### ISSUE TITLE
org.asteriskjava.manager.internal.EventBuilderImpl

### ISSUE THREAD

**Issue by mcbovice** [asterisk-java/asterisk-java#123]
----From: nohup.agi.20160407.out---------------------------------------------

2016-04-07 16:49:32 [main] INFO  org.asteriskjava.fastagi.DefaultAgiServer  - Listening on *:4573.
2016-04-07 16:49:51 [main] INFO  org.asteriskjava.fastagi.DefaultAgiServer  - Received connection from /45.63.68.90
2016-04-07 16:49:51 [main] INFO  org.asteriskjava.fastagi.DefaultAgiServer  - Thread pool started.
2016-04-07 16:49:51 [Asterisk-Java DaemonPool-1-thread-1] INFO  org.asteriskjava.fastagi.ResourceBundleMappingStrategy  - Added mapping for 'incoming.agi' to class com.vtiger.apps.asterisk.agi.actions.IncomingCall
2016-04-07 16:49:51 [Asterisk-Java DaemonPool-1-thread-1] ERROR org.asteriskjava.fastagi.internal.FastAgiConnectionHandler  - Unexpected Exception while handling request
java.lang.NullPointerException
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.asteriskjava.fastagi.AbstractMappingStrategy.createAgiScriptInstance(AbstractMappingStrategy.java:117)
	at org.asteriskjava.fastagi.ClassNameMappingStrategy.determineScript(ClassNameMappingStrategy.java:96)
	at org.asteriskjava.fastagi.CompositeMappingStrategy.determineScript(CompositeMappingStrategy.java:114)
	at org.asteriskjava.fastagi.internal.AgiConnectionHandler.run(AgiConnectionHandler.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

-----------From: nohup.webapp.20160407.out------------------------------------------------

2016-04-07 16:49:33 [main] INFO  org.eclipse.jetty.server.Server  - jetty-8.1.14.v20131031
2016-04-07 16:49:33 [main] INFO  org.eclipse.jetty.webapp.StandardDescriptorProcessor  - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2016-04-07 16:49:33 [main] INFO  org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:8383
2016-04-07 16:49:47 [qtp1750458075-16] INFO  a  - Outbound Call
2016-04-07 16:49:47 [qtp1750458075-16] INFO  a  - Asterisk Login Successfull
2016-04-07 16:49:47 [qtp1750458075-16] INFO  a  - Successfully Authenticated Vtiger Secret Key
2016-04-07 16:49:47 [qtp1750458075-16] INFO  org.asteriskjava.manager.internal.ManagerConnectionImpl  - Connecting to 45.*.*.*:5038
2016-04-07 16:49:47 [Asterisk-Java ManagerConnection-0-Reader-0] INFO  org.asteriskjava.manager.internal.ManagerConnectionImpl  - Connected via Asterisk Call Manager/1.3
2016-04-07 16:49:47 [Asterisk-Java ManagerConnection-0-Reader-0] WARN  org.asteriskjava.manager.internal.ManagerConnectionImpl  - Unsupported protocol version 'Asterisk Call Manager/1.3'. Use at your own risk.
2016-04-07 16:49:47 [Asterisk-Java ManagerConnection-0-Reader-0] INFO  org.asteriskjava.manager.internal.EventBuilderImpl  - No event class registered for event type 'fullybooted', attributes: {status=Fully Booted, event=FullyBooted, privilege=system,all}. Please report at http://jira.reucon.org/browse/AJ
2016-04-07 16:49:47 [qtp1750458075-16] INFO  org.asteriskjava.manager.internal.ManagerConnectionImpl  - Successfully logged in
2016-04-07 16:49:49 [qtp1750458075-16] INFO  org.asteriskjava.manager.internal.ManagerConnectionImpl  - Determined Asterisk version: Asterisk 1.6
2016-04-07 16:49:49 [qtp1750458075-16] INFO  a  - Sending call originate request to asterisk
2016-04-07 16:49:51 [qtp1750458075-16] INFO  a  - Context:vtiger
2016-04-07 16:49:51 [qtp1750458075-16] INFO  a  - From: 14 -> To: 317*******
2016-04-07 16:49:51 [qtp1750458075-16] INFO  a  - Outgoing Call Response: Success
2016-04-07 16:49:51 [qtp1750458075-16] INFO  a  - Asterisk Response: Originate successfully queued
2016-04-07 16:49:51 [Asterisk-Java ManagerConnection-0-Reader-0] WARN  org.asteriskjava.manager.internal.EventBuilderImpl  - Unable to set property 'connectedlinenum' to '3174145734' on org.asteriskjava.manager.event.NewStateEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
2016-04-07 16:49:51 [Asterisk-Java ManagerConnection-0-Reader-0] WARN  org.asteriskjava.manager.internal.EventBuilderImpl  - Unable to set property 'connectedlinenum' to '3174145734' on org.asteriskjava.manager.event.NewStateEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
2016-04-07 16:49:51 [Asterisk-Java ManagerConnection-0-Reader-0] INFO  org.asteriskjava.manager.internal.EventBuilderImpl  - No event class registered for event type 'softhanguprequest', attributes: {uniqueid=1460062189.0, cause=16, event=SoftHangupRequest, privilege=call,all, channel=SIP/14-00000000}. Please report at http://jira.reucon.org/browse/AJ
2016-04-07 16:49:51 [Asterisk-Java ManagerConnection-0-Reader-0] WARN  org.asteriskjava.manager.internal.EventBuilderImpl  - Unable to set property 'connectedlinename' to '<unknown>' on org.asteriskjava.manager.event.HangupEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
2016-04-07 16:49:51 [Asterisk-Java ManagerConnection-0-Reader-0] WARN  org.asteriskjava.manager.internal.EventBuilderImpl  - Unable to set property 'connectedlinenum' to '317*******' on org.asteriskjava.manager.event.HangupEvent: no setter. Please report at http://jira.reucon.org/browse/AJ

**Comment by mcbovice** [comment]
I can dial out on vtiger and connect my softphone however when I answer my softphone to dial out the number it then immediately stops the and hangs the call up

**Comment by bsutton** [comment]
So the warning Unable to set property 'connectedlinenum' isn't material. You can easily fix it by adding a setter/getter on the event.

the real problem looks to be an NPE which I'm guessing is being generated by your class com.vtiger.apps.asterisk.agi.actions.IncomingCall when the agi handler tries to instantiate it.
