### ISSUE TITLE
Caused by: java.lang.NumberFormatException: For input string: "0.0000"

### ISSUE THREAD

**Issue by nsrajpoot** [asterisk-java/asterisk-java#165]
Hello,

I'm using vtiger Asterisk connector and getting number formating problem.

Please help!

Thanks

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.asteriskjava.manager.internal.AbstractBuilder.setAttributes(AbstractBuilder.java:122)
    at org.asteriskjava.manager.internal.EventBuilderImpl.buildEvent(EventBuilderImpl.java:282)
    at org.asteriskjava.manager.internal.ManagerReaderImpl.buildEvent(ManagerReaderImpl.java:341)
    at org.asteriskjava.manager.internal.ManagerReaderImpl.run(ManagerReaderImpl.java:217)
    at java.lang.Thread.run(Thread.java:745)
**Caused by: java.lang.NumberFormatException: For input string: "0.0000"**
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:589)
    at java.lang.Long.parseLong(Long.java:631)
    at org.asteriskjava.manager.event.AbstractRtcpEvent.secStringToLong(AbstractRtcpEvent.java:101)
    at org.asteriskjava.manager.event.RtcpReceivedEvent.setRtt(RtcpReceivedEvent.java:202)
    ... 9 more

**Comment by towe75** [comment]
See #173 
Somebody else and me had same problem. Maybe a maintainer can close this as duplicate?

**Comment by bsutton** [comment]
closed as duplicate
