### ISSUE TITLE
On socket error managerconnection state is still connected

### ISSUE THREAD

**Issue by pk1057** [asterisk-java/asterisk-java#167]
Hello,
the attached  exception occurred on a production system.
It seems that the state of the Manager Connection keeps CONNECTED even if there is an connection exception.
When i looked throught the code it seems for me that the manager connection doesn't change the state due to an network communication error 

```
2016-09-12 11:44:56,871 WARN  [Asterisk-Java Ping-0]  de.will.obelisk.asterisk.AsteriskManager - Exception on sending Ping to DefaultManagerConnection[hostname='172.24.244.164',port=5038]
java.net.SocketException: Datenübergabe unterbrochen (broken pipe)
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
    at java.io.BufferedWriter.write(BufferedWriter.java:230)
    at java.io.Writer.write(Writer.java:157)
    at org.asteriskjava.util.internal.SocketConnectionFacadeImpl.write(SocketConnectionFacadeImpl.java:214)
    at org.asteriskjava.manager.internal.ManagerWriterImpl.sendAction(ManagerWriterImpl.java:76)
    at org.asteriskjava.manager.internal.ManagerConnectionImpl.sendAction(ManagerConnectionImpl.java:960)
    at org.asteriskjava.manager.internal.ManagerConnectionImpl.sendAction(ManagerConnectionImpl.java:876)
    at org.asteriskjava.manager.DefaultManagerConnection.sendAction(DefaultManagerConnection.java:330)
    at de.will.obelisk.asterisk.AsteriskManager$1.ping(AsteriskManager.java:52)
    at org.asteriskjava.manager.PingThread.run(PingThread.java:178)
```

**Comment by bsutton** [comment]
The manager connection logic has been re-worked so I'm going to close this now as it is probably no longer applicable given the extensive changes.
