### ISSUE TITLE
Unsupported protocol version 'Asterisk Call Manager/2.10.0 (openNMS)

### ISSUE THREAD

**Issue by clandestinox** [asterisk-java/asterisk-java#200]
Dears

I need conect with opennms plataforms  but i can´t because i have this error

![image](https://cloud.githubusercontent.com/assets/29131990/26701540/8f4a9ac6-46ef-11e7-87fb-8cbb3193b01b.png)

The version of asterisk is the "13.15.0"
The version opennms plataform is "19.1.0"

The ami Configuration OpenNMS

<?xml version="1.0"?>
<ami-config retry="2" timeout="1500"
        username="opennms" password="dj3ldr3s">
</ami-config>
[asterisk-configuration.properties.txt](https://github.com/asterisk-java/asterisk-java/files/1046123/asterisk-configuration.properties.txt)
[maillog-asterisk.txt](https://github.com/asterisk-java/asterisk-java/files/1046125/maillog-asterisk.txt)
[manager-conf-asterisk.txt](https://github.com/asterisk-java/asterisk-java/files/1046124/manager-conf-asterisk.txt)

Helpme please

Thanks!

**Comment by bsutton** [comment]
opennms?

You are going to have to provide more detail as to what you are trying 
to do.

**Comment by clandestinox** [comment]
The openNMS is a monitoring plataform  and this  use "asterisk-java" to connect  to asterisk pbx, when i want to connect  it rejects the connection 


2017-06-02 10:24:13,179 WARN  [Asterisk-Java ManagerConnection-0-Reader-0] o.a.m.i.ManagerConnectionImpl: Unsupported protocol version 'Asterisk Call Manager/2.10.0'. Use at your own risk.
2017-06-02 10:24:14,190 ERROR [Thread-2113] o.o.n.n.a.AsteriskOriginateNotificationStrategy: Error originating call for notification.
org.opennms.netmgt.asterisk.utils.AsteriskOriginatorException: Authentication failure logging in Asterisk manager connection
        at org.opennms.netmgt.asterisk.utils.AsteriskOriginator.originateCall(AsteriskOriginator.java:203) ~[opennms-asterisk-19.1.0.jar:?]
        at org.opennms.netmgt.notifd.asterisk.AsteriskOriginateNotificationStrategy.send(AsteriskOriginateNotificationStrategy.java:68) [opennms-asterisk-19.1.0.jar:?]
        at org.opennms.netmgt.notifd.ClassExecutor.execute(ClassExecutor.java:69) [opennms-services-19.1.0.jar:?]
        at org.opennms.netmgt.notifd.NotificationTask.run(NotificationTask.java:267) [opennms-services-19.1.0.jar:?]
Caused by: org.asteriskjava.manager.AuthenticationFailedException: Authentication failed
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.doLogin(ManagerConnectionImpl.java:616) ~[asterisk-java.jar:?]
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(ManagerConnectionImpl.java:480) ~[asterisk-java.jar:?]
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(ManagerConnectionImpl.java:465) ~[asterisk-java.jar:?]
        at org.asteriskjava.manager.DefaultManagerConnection.login(DefaultManagerConnection.java:309) ~[asterisk-java.jar:?]
        at org.opennms.netmgt.asterisk.utils.AsteriskOriginator.originateCall(AsteriskOriginator.java:197) ~[opennms-asterisk-19.1.0.jar:?]
        ... 3 more

**Comment by seanbright** [comment]
The error indicates an authentication failure, meaning that you provided the wrong username and password for the manager user. The "Unsupported protocol version" warning is just a warning and is not causing this.

**Comment by seanbright** [comment]
This does not appear to be an Asterisk-Java issue, but a configuration one. Feel free to re-open if you believe that is not the case.
