### ISSUE TITLE
Unable to convert value (report0iajitter)

### ISSUE THREAD

**Issue by mr-mister123** [asterisk-java/asterisk-java#204]
Hi all together.

I'm using current version from master of asterisk-java.
Sometimes i am getting exceptions while setting report0iajitter-property on RtcpReceivedEvent:

`ERROR internal.EventBuilderImpl (AbstractBuilder.java:142): Unable to convert value: Called the constructor of class java.lang.Integer with value '4007233764' for the attribute 'report0iajitter'
 of event type org.asteriskjava.manager.event.RtcpReceivedEvent with resulting error: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor55.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.asteriskjava.manager.internal.AbstractBuilder.setAttributes(AbstractBuilder.java:138)
        at org.asteriskjava.manager.internal.EventBuilderImpl.buildEvent(EventBuilderImpl.java:433)
        at org.asteriskjava.manager.internal.ManagerReaderImpl.buildEvent(ManagerReaderImpl.java:363)
        at org.asteriskjava.manager.internal.ManagerReaderImpl.run(ManagerReaderImpl.java:229)
        at java.lang.Thread.run(Thread.java:724)

Caused by: java.lang.NumberFormatException: For input string: "4007233764"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:495)
        at java.lang.Integer.<init>(Integer.java:677)
        ... 8 more`

Sometimes there seem to be jitter-values transmitted by the server that do not fit within an integer value...

We are using asterisk version 13.14.1.

Thanks,
Karsten

**Comment by bsutton** [comment]
Can you submit a patch with a type of Long.

**Comment by mr-mister123** [comment]
Created pull request: #205
