### ISSUE TITLE
Response to CommandAction("sip show peer [user id]")

### ISSUE THREAD

**Issue by gfbiltz** [asterisk-java/asterisk-java#300]
The following error does not occur with the same code working with Asterisk 11 but does occur with Asterisk 16 (Master Branch of asterisk-Java.jar).   The following shows in the Tomcat9-stderr.log.

org.asteriskjava.live.ManagerCommunicationException: Response to CommandAction("sip show peer 2480") was not a CommandResponse but org.asteriskjava.manager.response.ManagerError: actionId='null'; message='Command output follows'; response='Error'; uniqueId='null'; systemHashcode=337430947
	at org.asteriskjava.live.internal.AsteriskServerImpl.executeCliCommand(AsteriskServerImpl.java:804)
	at org.asteriskjava.live.DefaultAsteriskServer.executeCliCommand(DefaultAsteriskServer.java:252)
	at com.interop.commonutil.AsteriskManager.isDeviceActive(AsteriskManager.java:448)
	at com.interop.radioswitch.SIPHub.getMode(SIPHub.java:3032)
	at com.interop.config.SwitchInit.getMode(SwitchInit.java:2179)
	at com.interop.config.SwitchInit.refreshSwitchSlotDisplays(SwitchInit.java:853)
	at com.interop.config.SwitchInit$SwitchListener.run(SwitchInit.java:4959)
	at java.lang.Thread.run(Unknown Source)

**Comment by seanbright** [comment]
I am not able to reproduce this with 3.39.0. If you are able to reproduce this with 3.39.0 please provide detailed instructions so that we can try to replicate it locally.
