### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/reflections/Reflections

### ISSUE THREAD

**Issue by sadzas** [asterisk-java/asterisk-java#332]
Hi everybody:

I'm using asterisk-java-2.04 since 2018. Right now I wanted to update to 3.5. Compiling was ok but when I want to use it with my app I see the following:

Exception in thread "main" java.lang.NoClassDefFoundError: org/reflections/Reflections
	at org.asteriskjava.manager.internal.EventBuilderImpl.<clinit>(EventBuilderImpl.java:55)
	at org.asteriskjava.manager.internal.ManagerReaderImpl.<init>(ManagerReaderImpl.java:112)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.createReader(ManagerConnectionImpl.java:265)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.connect(ManagerConnectionImpl.java:740)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.doLogin(ManagerConnectionImpl.java:536)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(ManagerConnectionImpl.java:485)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(ManagerConnectionImpl.java:470)
	at org.asteriskjava.manager.DefaultManagerConnection.login(DefaultManagerConnection.java:309)
	at manager.LibManagerEvents.escuchar(LibManagerEvents.java:88)
	at manager.LibManagerEvents.run(LibManagerEvents.java:83)
	at matecore.Main.main(Main.java:149)

I'm not sure what is wrong and I can't find any answer.

Please, could you help me?

Thanks!

**Comment by sadzas** [comment]
I'm sorry... my bad. A classpath issue.
