### ISSUE TITLE
ExceptionInInitializerError and zip file closed

### ISSUE THREAD

**Issue by maoqq10** [asterisk-java/asterisk-java#347]
if I package project as a springboot jar,it will alert "java.lang.IllegalStateException: zip file closed" and " java.lang.ExceptionInInitializerError" when i run the jar.
when i package project as a springboot war and run it in tomcat,everything is ok.

Here is the error message:
Exception in thread "Thread-3" java.lang.ExceptionInInitializerError
        at org.asteriskjava.manager.internal.ManagerReaderImpl.<init>(ManagerRea
derImpl.java:112)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.createReader(
ManagerConnectionImpl.java:265)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.connect(Manag
erConnectionImpl.java:740)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.doLogin(Manag
erConnectionImpl.java:536)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(Manager
ConnectionImpl.java:485)
        at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(Manager
ConnectionImpl.java:470)
        at org.asteriskjava.manager.DefaultManagerConnection.login(DefaultManage
rConnection.java:309)
        at com.njrzkj.wireless_server.service.Asterisk_Service.connect(Asterisk_
Service.java:132)
        at com.njrzkj.wireless_server.service.Asterisk_Service$1.run(Asterisk_Se
rvice.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
        at java.util.zip.ZipFile.access$200(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipEntryIterator.<init>(ZipFile.java:499)
        at java.util.zip.ZipFile.entries(ZipFile.java:552)
        at java.util.jar.JarFile.access$001(JarFile.java:71)
        at java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:250)
        at java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:247)
        at java.util.jar.JarFile.stream(JarFile.java:279)
        at org.reflections.vfs.ZipDir.lambda$getFiles$2(ZipDir.java:21)
        at org.reflections.Reflections.scan(Reflections.java:260)
        at org.reflections.Reflections.scan(Reflections.java:216)
        at org.reflections.Reflections.<init>(Reflections.java:137)
        at org.reflections.Reflections.<init>(Reflections.java:182)
        at org.reflections.Reflections.<init>(Reflections.java:155)
        at org.asteriskjava.manager.internal.EventBuilderImpl.<clinit>(EventBuil
derImpl.java:55)
        ... 10 more

and my code is:
       asteriskServer=new DefaultAsteriskServer(ip,port,username,password);
       asteriskServer.addAsteriskServerListener(aspl);
       conn=asteriskServer.getManagerConnection();
       conn.login();

**Comment by jefaokpta** [comment]
Hi maoqq10 same problem here (in spring version 2.3.5.RELEASE).
However, i had good news! In version 2.3.1.RELEASE runs ok!

**Comment by maoqq10** [comment]
@jefaokpta  Thanks, You got that right. Spring boot 2.3.1~2.3.3 can run ok.
