### ISSUE TITLE
Unable to login: Timeout waiting for protocol identifier

### ISSUE THREAD

**Issue by VanHelsing79** [asterisk-java/asterisk-java#356]
I just starting dabbling around with asterisk-java. 
We do have Asterisk 13.15.1 running.

I have the following problem:
If I use the asterisk-java-2.0.3.jar and try this:
```asteriskServer = new DefaultAsteriskServer("192.168.205.210", "manager", "xxx");```
it works. 

Console shows this:
```Nov 09, 2020 1:27:41 PM org.asteriskjava.manager.internal.ManagerConnectionImpl connect
INFORMATION: Connecting to 192.168.205.210:5038
Nov 09, 2020 1:27:41 PM org.asteriskjava.manager.internal.ManagerConnectionImpl setProtocolIdentifier
INFORMATION: Connected via Asterisk Call Manager/2.10.0
Nov 09, 2020 1:27:41 PM org.asteriskjava.manager.internal.ManagerConnectionImpl setProtocolIdentifier
WARNUNG: Unsupported protocol version 'Asterisk Call Manager/2.10.0'. Use at your own risk.
Nov 09, 2020 1:27:41 PM org.asteriskjava.manager.internal.ManagerConnectionImpl doLogin
INFORMATION: Successfully logged in
Nov 09, 2020 1:27:42 PM org.asteriskjava.manager.internal.ManagerConnectionImpl doLogin
INFORMATION: Determined Asterisk version: Asterisk 13
```

However if I use the latest release 3.8.0 with the same code as above, the result is:

```
13:24:05.767 [main] INFO  o.a.m.internal.ManagerConnectionImpl - Connecting to 192.168.205.210:5038
13:24:05.769 [main] DEBUG o.a.m.internal.ManagerConnectionImpl - Creating reader for 192.168.205.210:5038
13:24:05.822 [main] DEBUG org.reflections.Reflections - going to scan these urls: [file:/C:/Users/XXX/git/asterisk-java/target/classes/]
13:24:05.969 [main] INFO  org.reflections.Reflections - Reflections took 144 ms to scan 1 urls, producing 31 keys and 209 values 
13:24:05.971 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.util.EventObject
13:24:05.971 [main] DEBUG org.reflections.Reflections - expanded subtype java.lang.Comparable -> java.lang.Enum
13:24:05.971 [main] DEBUG org.reflections.Reflections - expanded subtype java.io.Serializable -> java.lang.Enum
[...]
13:24:06.035 [main] DEBUG o.a.m.internal.ManagerConnectionImpl - Creating writer
13:24:06.036 [main] DEBUG o.a.m.internal.ManagerConnectionImpl - Creating socket
13:24:06.071 [main] DEBUG o.a.m.internal.ManagerConnectionImpl - Passing socket to reader
13:24:06.071 [main] DEBUG o.a.m.internal.ManagerConnectionImpl - Creating and starting reader thread
13:24:06.071 [main] DEBUG o.a.m.internal.ManagerConnectionImpl - Passing socket to writer
13:24:06.102 [Asterisk-Java ManagerConnection-0-Reader-0] DEBUG o.a.m.internal.ManagerConnectionImpl - Dispatching event:
org.asteriskjava.manager.event.DisconnectEvent[dateReceived='Mon Nov 09 13:24:06 CET 2020',server=null,calleridname=null,systemname=null,connectedlinename=null,priority=null,sequencenumber=null,channelstate=null,exten=null,calleridnum=null,context=null,connectedlinenum=null,channelstatedesc=null,timestamp=null,systemHashcode=1279611766]
13:24:08.073 [main] INFO  o.a.m.internal.ManagerConnectionImpl - Closing socket.
Exception in thread "main" Exception in thread "Asterisk-Java ManagerConnection-0-Reader-0" org.asteriskjava.live.ManagerCommunicationException: Unable to login: Timeout waiting for protocol identifier
	at org.asteriskjava.live.internal.AsteriskServerImpl.initializeIfNeeded(AsteriskServerImpl.java:261)
	at org.asteriskjava.live.internal.AsteriskServerImpl.addAsteriskServerListener(AsteriskServerImpl.java:849)
	at org.asteriskjava.live.DefaultAsteriskServer.addAsteriskServerListener(DefaultAsteriskServer.java:287)
	at com.culturall.asterisk.AsteriskTester.run(AsteriskTester.java:33)
	at com.culturall.asterisk.AsteriskTester.main(AsteriskTester.java:90)
Caused by: org.asteriskjava.manager.TimeoutException: Timeout waiting for protocol identifier
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.doLogin(ManagerConnectionImpl.java:560)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(ManagerConnectionImpl.java:487)
	at org.asteriskjava.manager.internal.ManagerConnectionImpl.login(ManagerConnectionImpl.java:472)
	at org.asteriskjava.manager.DefaultManagerConnection.login(DefaultManagerConnection.java:309)
	at org.asteriskjava.live.internal.AsteriskServerImpl.initializeIfNeeded(AsteriskServerImpl.java:257)
	... 4 more
java.lang.NoSuchMethodError: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
	at org.asteriskjava.util.internal.streamreader.FastScannerNl.next(FastScannerNl.java:66)
	at org.asteriskjava.util.internal.SocketConnectionFacadeImpl.readLine(SocketConnectionFacadeImpl.java:202)
	at org.asteriskjava.manager.internal.ManagerReaderImpl.run(ManagerReaderImpl.java:163)
	at java.lang.Thread.run(Unknown Source)
```
I searched the code in hope of finding some changes, that might cause this but I didn't find anything.

Please help! :)

**Comment by VanHelsing79** [comment]
I was able to resolve the issue. I had to change 'useLegacyScanner' in FastScannerFactory from false to true. That made the connection work.
