### ISSUE TITLE
Not able to connect to Asterisk through Getting Started documentation on Asterisk 18 and Asterisk-Java 3.14.0

### ISSUE THREAD

**Issue by dhartvigsenAmerisave** [asterisk-java/asterisk-java#373]
I have an existing project that I use in an enterprise environment. The production environment is using Asterisk 1.4.44, using OrderlyCalls to connect the Java application.  In a development environment, this project is able to connect to Asterisk 18.7.1 from orderlycalls (which is not idea since it was last updated 7 years ago, but creating a separate servlet to run the Asterisk-java getting started section from this github wiki, I get a "Timeout waiting for protocol identifier", which is served up on the webpage where I configured the servlet.  I also decided to start a separate springboot project where I just include the basic information from getting started section with similar results:

 `2021-11-30 16:14:53.909  INFO 34160 --- [           main] c.a.a.AsteriskJavaSpringTestApplication  : Started AsteriskJavaSpringTestApplication in 1.31 seconds (JVM running for 1.896)
2021-11-30 16:14:53.926  INFO 34160 --- [           main] o.a.m.internal.ManagerConnectionImpl     : Connecting to 70.42.180.52:5060
2021-11-30 16:14:53.975  INFO 34160 --- [           main] org.reflections.Reflections              : Reflections took 41 ms to scan 1 urls, producing 32 keys and 219 values 
2021-11-30 16:14:54.028  INFO 34160 --- [:AsyncEventPump] o.a.manager.internal.AsyncEventPump      : starting
2021-11-30 16:14:54.039  INFO 34160 --- [tion-0-Reader-0] o.a.manager.internal.AsyncEventPump      : Asterisk-Java ManagerConnection-0-Reader-0:AsyncEventPump Requesting AsyncEventPump to stop
2021-11-30 16:14:56.034  INFO 34160 --- [           main] o.a.m.internal.ManagerConnectionImpl     : Closing socket.
2021-11-30 16:14:56.036  WARN 34160 --- [:AsyncEventPump] o.a.manager.internal.AsyncEventPump      : The following message will only appear once per second!
Event dispatched 1996 MS after arriving, your ManagerEvent handlers are too slow!
You should also check for Garbage Collection issues.
There are 0 events waiting to be processed in the queue.
Event was Poison
2021-11-30 16:14:56.036  WARN 34160 --- [:AsyncEventPump] o.a.manager.internal.AsyncEventPump      : AsyncEventPump has exited
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.asteriskjava.pbx.PBXFactory.getActivePBX(PBXFactory.java:12)
	at org.asteriskjava.pbx.PBXFactory.init(PBXFactory.java:21)
	at com.amerisave.asteriskjavaspringtest.AsteriskJavaSpringTestApplication.initialize(AsteriskJavaSpringTestApplication.java:28)
	at com.amerisave.asteriskjavaspringtest.AsteriskJavaSpringTestApplication.main(AsteriskJavaSpringTestApplication.java:18)
Caused by: java.lang.RuntimeException: org.asteriskjava.manager.TimeoutException: Timeout waiting for protocol identifier`  

Is there something missing from the wiki that I need to know in order to connect Asterisk-Java to my Asterisk server?  Another interesting point is that I get the same stack trace when the Asterisk server is not running, which means is not connecting despite all ports being completely open on the Asterisk server, and using the default port to connect.

**Comment by dhartvigsenAmerisave** [comment]
The default port being passed through was incorrect.  I overrode the getManagerPort and returned the correct port of 5038.  As you could see above in the log, the port being passed through was 5060, which is not the default port for AMI.
